#!/bin/sh
DST=${1:-images}

. $(dirname $0)/functions.sh

export LIBGUESTFS_BACKEND=direct
export LIBGUESTFS_MEMSIZE=2048

mkdir -p "$DST"

run ./mkimage.alpine "https://alpine.global.ssl.fastly.net/alpine/v3.10/releases/x86_64/alpine-minirootfs-3.10.0-x86_64.tar.gz" "$DST/alpine-3.10.qcow2" 500M
run ./mkimage.ubuntu "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img" "$DST/ubuntu-18.04.qcow2" 2G
run ./mkimage.ubuntu "https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img" "$DST/ubuntu-16.04.qcow2" 2G
run ./mkimage.debian "https://cdimage.debian.org/cdimage/openstack/current/debian-9.9.3-20190618-openstack-amd64.qcow2" "$DST/debian-9.qcow2" 2G
run ./mkimage.devuan "https://mirror.leaseweb.com/devuan/devuan_ascii/virtual/devuan_ascii_2.0.0_amd64_qemu.qcow2.xz" "$DST/devuan-2.qcow2" 2G
run ./mkimage.centos6 "https://cloud.centos.org/centos/6/images/CentOS-6-x86_64-GenericCloud.qcow2c" "$DST/centos-6.qcow2" 2G
run ./mkimage.centos7 "https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2c" "$DST/centos-7.qcow2" 2G
run ./mkimage.fedora "https://download.fedoraproject.org/pub/fedora/linux/releases/30/Cloud/x86_64/images/Fedora-Cloud-Base-30-1.2.x86_64.qcow2" "$DST/fedora-30.qcow2" 2G
run ./mkimage.opensuse "https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.1/images/openSUSE-Leap-15.1-OpenStack.x86_64.qcow2" "$DST/opensuse-leap-15.qcow2" 2G
